# Generated by Django 6.0.6 on 2026-09-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_validation_and_constraints'),
        ('students', '0002_alter_profile_profile_picture'),
    ]

    operations = [
    ]
